name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          python app.py

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Build and push frontend Docker image
        uses: actions/checkout@v3
        with:
          context: frontend
          push: true
          tags: fe584zg46sd5f48g8re/frontend:latest

      - name: Build and push backend Docker image
        uses: actions/checkout@v3
        with:
          context: backend
          push: true
          tags: fe584zg46sd5f48g8re/backend:latest
